### ISSUE TITLE
Create service for sending sms

### ISSUE THREAD

**Issue by urosjarc** [Programerski-klub-Ljubljana/sms_sender#40]
Service should check on every 15 min check if its time to send an SMS to students 2 hours before the meeting.
Make sure that the service will not send SMS to the same student twice. Of course, create extensive tests for this important functionality. The settings for this service should be located in DB [settings] table so that user can change behavior of this feature on the fly.

All of the student infos you can get in calendar event: [google_calendar_event.pdf](https://github.com/Danilo-Danijel-team/sms_sender/files/9611319/gmail.pdf)

All assignees: @ethernal12 @danilojezernik collaborate together to create solution on your own, I'm giving you guys a chance to prove yourself 🥇. Let me see how much you two progress.

**Comment by urosjarc** [comment]
@ethernal12 , @danilojezernik Tukaj naj se dodaja vse kar se tiče sms-sender servica. Ker kot sem že povedal je to feature ki je tako pomemben da si zasluži svoj branch in pull request.

**Comment by danilojezernik** [comment]
Problem, je, ker projekt #10  ni mergan in manjka en kup stvari, da bi lahko naredil in morda testiral vse skupaj. Se lahko kako zadeva merga, da lahko potem brench vsebuje vse potrebne route in file?

**Comment by urosjarc** [comment]
Ja iz tistega brancha pulli spremembe v branch na katerem ti manjkajo stvari.

**Comment by danilojezernik** [comment]
@urosjarc Ajaaaa... to se tako lahko dela. Evo pulano :)

**Comment by urosjarc** [comment]
@danilojezernik Potem ko bo ta branch mergan v master boš pa še en pull naredil da boš sinhroniziran z masterjem.
In ne boš imel nič problemov.

**Comment by urosjarc** [comment]
@danilojezernik Na branchih ki so namenjeni za development lahko delaš kar koli hočeš, samo master (produkcijski branchi) morajo biti tipi topi in spremembe se v njih dodajajo samo preko pull requestov. Če vidva z korbijem delata na isti stvari delata vsak na svojem branchu in potem pulata spremembe drug drugega.

**Comment by danilojezernik** [comment]
@urosjarc : Mi tale github in vso delovanje in uporaba le tega postaja vse bolj jasna. Top! Hvala!

**Comment by danilojezernik** [comment]
@urosjarc @ethernal12 : Upam, da je začetek arhitekture in funkcionalnosti routa za testiranje intervalnega pošiljanja smsov ok? 😟

**Comment by urosjarc** [comment]
@danilojezernik Če boš potreboval kakšno dodatno pomoč me pingi, tole je najtežji del razvoja tako da pričakujem višjo frekvenco vprašanj.

**Comment by danilojezernik** [comment]
@urosjarc @ethernal12 : Trenutno se ukvarjam z ekstrakcijo vrednosti `end` (vrednost: 1) in `start` (vrednost: 2) iz podatkovne baze, ampak imamo eno težavo. Problem pa nastane, ker moramo čas, ki se je ustvaril (glej twoHoursAfterCurrent) v smsSender.js, ustvariti tako rekoč na roke. --> new Date(Date.now()) vrne čas: 2022-10-10T07:38:41.895Z in če nanj prištejemo karkoli, se ne seštevajo ure, ampak se na konec dodaja vrednost, ki so se "prištele" oziroma "dodale" na konec časa ( + 4 + hourConstant); vrednost je potem nekaj takšnega: 2022-10-10T07:38:41.895Z46102390.

Sicer sem zadevo uredil tako, da sem new Date izbrisal in uporabil samo Date.now().

Zdej sam sem sicer ustvaril funkcijo hoursAfterCurrent, ki vrača datum, ki je trenutni čas, ampak bi morala z @ethernal12 implementirat to v kodo. Ko boš @ethernal12 imel čas, mi javi, da se dobima in pogledava zadevo, da lahko testiraš.

**Comment by ethernal12** [comment]
@danilojezernik Bom danes popoldne pullov, pa bom pogledau in se slišiva.
